using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rally.Framework.System
{
    public class ModuleConfiguration
    {
        //public static string SQL_CMD_InsertApplicationSetting = "INSERT INTO application_settings (PlatformIpAddress, PlatformPortNumber, AlarmMode, AlarmSound, NotificationMode, NotificationSound, Language) VALUES (@PlatformIpAddress, @PlatformPortNumber, @AlarmMode, @AlarmSound, @NotificationMode, @NotificationSound, @Language);";
        //public static string SQL_CMD_UpdateApplicationSetting = "UPDATE application_settings SET PlatformIpAddress = @PlatformIpAddress, PlatformPortNumber = @PlatformPortNumber, AlarmMode = @AlarmMode, AlarmSound = @AlarmSound, NotificationMode = @NotificationMode, NotificationSound = @NotificationSound, Language = @Language WHERE ID = @ID;";
        //public static string SQL_CMD_SelectApplicationSettings = "SELECT ID, PlatformIpAddress, PlatformPortNumber, AlarmMode, AlarmSound, NotificationMode, NotificationSound, Language FROM application_settings;";
        //public static string SQL_CMD_SelectApplicationSettingById = "SELECT ID, PlatformIpAddress, PlatformPortNumber, AlarmMode, AlarmSound, NotificationMode, NotificationSound, Language FROM application_settings WHERE ID = @ID;";
        //public static string SQL_CMD_SelectMaxApplicationSettingID = "SELECT MAX(ID) FROM application_settings";

        //public static string SQL_CMD_InsertApplicationSetting = "INSERT INTO tb_mon_ApplicationSettings (app_PlatformIpAddress, app_PlatformPortNumber, app_AlarmMode, app_AlarmSound, app_NotificationMode, app_NotificationSound, app_Language) VALUES (@PlatformIpAddress, @PlatformPortNumber, @AlarmMode, @AlarmSound, @NotificationMode, @NotificationSound, @Language);";
        ////public static string SQL_CMD_UpdateApplicationSetting = "UPDATE tb_mon_ApplicationSettings SET app_PlatformIpAddress = @PlatformIpAddress, app_PlatformPortNumber = @PlatformPortNumber, app_AlarmMode = @AlarmMode, app_AlarmSound = @AlarmSound, app_NotificationMode = @NotificationMode, app_NotificationSound = @NotificationSound, app_Language = @Language WHERE app_ID = @ID;";
        //public static string SQL_CMD_UpdateApplicationSetting = "UPDATE tb_mon_ApplicationSettings SET app_PlatformIpAddress = @PlatformIpAddress, app_PlatformPortNumber = @PlatformPortNumber, app_AlarmMode = @AlarmMode, app_AlarmSound = @AlarmSound, app_NotificationMode = @NotificationMode, app_NotificationSound = @NotificationSound, app_Language = @Language,app_name=@PlatformName,app_Protocol=@PlatformProtocol,app_name2=@PlatformName2,app_PlatformIpAddress2=@PlatformIpAddress2,app_PlatformPortNumber2=@PlatformPortNumber2,app_Protocol2=@PlatformProtocol2,app_name3=@PlatformName3,app_PlatformIpAddress3=@PlatformIpAddress3,app_PlatformPortNumber3=@PlatformPortNumber3,app_Protocol3=@PlatformProtocol3,app_name4=@PlatformName4,app_PlatformIpAddress4=@PlatformIpAddress4,app_PlatformPortNumber4=@PlatformPortNumber4,app_Protocol4=@PlatformProtocol4,app_theme=@PlatformTheme,app_time=@PlatformTime,app_type=@PlatformType,app_Duration2=@PlatformDuration2,app_Duration1=@PlatformDuration1,app_BgValArchFrequency=@BgValArchFrequency,app_ImageCapturingMode=@ImageCapturingMode,app_ImageCapturingCount=@ImageCapturingCount,app_VideoCapturingMode=@VideoCapturingMode,app_VideoCapturingLength=@VideoCapturingLength WHERE app_ID = @ID;";
        //public static string SQL_CMD_SelectApplicationSettings = "SELECT app_ID as ID, app_PlatformIpAddress as PlatformIpAddress, app_PlatformPortNumber as PlatformPortNumber, app_AlarmMode as AlarmMode, app_AlarmSound as AlarmSound, app_NotificationMode as NotificationMode, app_NotificationSound as NotificationSound, app_Language as Language,app_name as PlatformName,app_Protocol as PlatformProtocol,app_name2 as PlatformName2,app_PlatformIpAddress2 as PlatformIpAddress2,app_PlatformPortNumber2 as PlatformPortNumber2,app_Protocol2 as PlatformProtocol2,app_name3 as PlatformName3,app_PlatformIpAddress3 as PlatformIpAddress3,app_PlatformPortNumber3 as PlatformPortNumber3,app_Protocol3 as PlatformProtocol3,app_name4 as PlatformName4,app_PlatformIpAddress4 as PlatformIpAddress4,app_PlatformPortNumber4 as PlatformPortNumber4,app_Protocol4 as PlatformProtocol4,app_theme as PlatformTheme,app_time as PlatformTime,app_type as PlatformType,app_Duration2 as PlatformDuration2,app_Duration1 as PlatformDuration1,app_Duration1 as Alarmduration,app_Duration2 as Notificationduration,app_BgValArchFrequency as BgValArchFrequency,app_ImageCapturingMode as ImageCapturingMode,app_ImageCapturingCount as ImageCapturingCount,app_VideoCapturingMode as VideoCapturingMode,app_VideoCapturingLength as VideoCapturingLength FROM tb_mon_ApplicationSettings;";
        //public static string SQL_CMD_SelectApplicationSettingById = "SELECT app_ID as ID, app_PlatformIpAddress as PlatformIpAddress, app_PlatformPortNumber as PlatformPortNumber, app_AlarmMode as AlarmMode, app_AlarmSound as AlarmSound, app_NotificationMode as NotificationMode, app_NotificationSound as NotificationSound, app_Language as Language,app_name as PlatformName,app_Protocol as PlatformProtocol,app_name2 as PlatformName2,app_PlatformIpAddress2 as PlatformIpAddress2,app_PlatformPortNumber2 as PlatformPortNumber2,app_Protocol2 as PlatformProtocol2,app_name3 as PlatformName3,app_PlatformIpAddress3 as PlatformIpAddress3,app_PlatformPortNumber3 as PlatformPortNumber3,app_Protocol3 as PlatformProtocol3,app_name4 as PlatformName4,app_PlatformIpAddress4 as PlatformIpAddress4,app_PlatformPortNumber4 as PlatformPortNumber4,app_Protocol4 as PlatformProtocol4,app_theme as PlatformTheme,app_time as PlatformTime,app_type as PlatformType,app_Duration2 as PlatformDuration2,app_Duration1 as PlatformDuration1,app_Duration1 as Alarmduration,app_Duration2 as Notificationduration,app_BgValArchFrequency as BgValArchFrequency,app_ImageCapturingMode as ImageCapturingMode,app_ImageCapturingCount as ImageCapturingCount,app_VideoCapturingMode as VideoCapturingMode,app_VideoCapturingLength as VideoCapturingLength FROM tb_mon_ApplicationSettings WHERE app_ID = @ID;";
        //public static string SQL_CMD_SelectMaxApplicationSettingID = "SELECT MAX(app_ID) FROM tb_mon_ApplicationSettings"; 
        //public static string SQL_CMD_UpdateSetting = "UPDATE tb_mon_ApplicationSettings SET app_time=@PlatformTime,app_type=@PlatformType  WHERE app_ID = @ID;";

        public static string SQL_CMD_InsertApplicationSetting = "INSERT INTO ApplicationSettings (PlatformIpAddress, PlatformPortNumber, AlarmMode, AlarmSound, NotificationMode, NotificationSound, Language) VALUES (@PlatformIpAddress, @PlatformPortNumber, @AlarmMode, @AlarmSound, @NotificationMode, @NotificationSound, @Language);";
        //public static string SQL_CMD_UpdateApplicationSetting = "UPDATE ApplicationSettings SET PlatformIpAddress = @PlatformIpAddress, PlatformPortNumber = @PlatformPortNumber, AlarmMode = @AlarmMode, AlarmSound = @AlarmSound, NotificationMode = @NotificationMode, NotificationSound = @NotificationSound, Language = @Language WHERE ID = @ID;";
        public static string SQL_CMD_UpdateApplicationSetting = "UPDATE ApplicationSettings SET PlatformIpAddress = @PlatformIpAddress, PlatformPortNumber = @PlatformPortNumber, AlarmMode = @AlarmMode, AlarmSound = @AlarmSound, NotificationMode = @NotificationMode, NotificationSound = @NotificationSound, Language = @Language,name=@PlatformName,Protocol=@PlatformProtocol,name2=@PlatformName2,PlatformIpAddress2=@PlatformIpAddress2,PlatformPortNumber2=@PlatformPortNumber2,Protocol2=@PlatformProtocol2,name3=@PlatformName3,PlatformIpAddress3=@PlatformIpAddress3,PlatformPortNumber3=@PlatformPortNumber3,Protocol3=@PlatformProtocol3,name4=@PlatformName4,PlatformIpAddress4=@PlatformIpAddress4,PlatformPortNumber4=@PlatformPortNumber4,Protocol4=@PlatformProtocol4,theme=@PlatformTheme,time=@PlatformTime,type=@PlatformType,Duration2=@PlatformDuration2,Duration1=@PlatformDuration1,BgValArchFrequency=@BgValArchFrequency,ImageCapturingMode=@ImageCapturingMode,ImageCapturingCount=@ImageCapturingCount,VideoCapturingMode=@VideoCapturingMode,VideoCapturingLength=@VideoCapturingLength WHERE ID = @ID;";
        public static string SQL_CMD_SelectApplicationSettings = "SELECT ID as ID, PlatformIpAddress as PlatformIpAddress, PlatformPortNumber as PlatformPortNumber, AlarmMode as AlarmMode, AlarmSound as AlarmSound, NotificationMode as NotificationMode, NotificationSound as NotificationSound, Language as Language,name as PlatformName,Protocol as PlatformProtocol,name2 as PlatformName2,PlatformIpAddress2 as PlatformIpAddress2,PlatformPortNumber2 as PlatformPortNumber2,Protocol2 as PlatformProtocol2,name3 as PlatformName3,PlatformIpAddress3 as PlatformIpAddress3,PlatformPortNumber3 as PlatformPortNumber3,Protocol3 as PlatformProtocol3,name4 as PlatformName4,PlatformIpAddress4 as PlatformIpAddress4,PlatformPortNumber4 as PlatformPortNumber4,Protocol4 as PlatformProtocol4,theme as PlatformTheme,time as PlatformTime,type as PlatformType,Duration2 as PlatformDuration2,Duration1 as PlatformDuration1,Duration1 as Alarmduration,Duration2 as Notificationduration,BgValArchFrequency as BgValArchFrequency,ImageCapturingMode as ImageCapturingMode,ImageCapturingCount as ImageCapturingCount,VideoCapturingMode as VideoCapturingMode,VideoCapturingLength as VideoCapturingLength FROM ApplicationSettings;";
        public static string SQL_CMD_SelectApplicationSettingById = "SELECT ID as ID, PlatformIpAddress as PlatformIpAddress, PlatformPortNumber as PlatformPortNumber, AlarmMode as AlarmMode, AlarmSound as AlarmSound, NotificationMode as NotificationMode, NotificationSound as NotificationSound, Language as Language,name as PlatformName,Protocol as PlatformProtocol,name2 as PlatformName2,PlatformIpAddress2 as PlatformIpAddress2,PlatformPortNumber2 as PlatformPortNumber2,Protocol2 as PlatformProtocol2,name3 as PlatformName3,PlatformIpAddress3 as PlatformIpAddress3,PlatformPortNumber3 as PlatformPortNumber3,Protocol3 as PlatformProtocol3,name4 as PlatformName4,PlatformIpAddress4 as PlatformIpAddress4,PlatformPortNumber4 as PlatformPortNumber4,Protocol4 as PlatformProtocol4,theme as PlatformTheme,time as PlatformTime,type as PlatformType,Duration2 as PlatformDuration2,Duration1 as PlatformDuration1,Duration1 as Alarmduration,Duration2 as Notificationduration,BgValArchFrequency as BgValArchFrequency,ImageCapturingMode as ImageCapturingMode,ImageCapturingCount as ImageCapturingCount,VideoCapturingMode as VideoCapturingMode,VideoCapturingLength as VideoCapturingLength FROM ApplicationSettings WHERE ID = @ID;";
        public static string SQL_CMD_SelectMaxApplicationSettingID = "SELECT MAX(ID) FROM ApplicationSettings";
        public static string SQL_CMD_UpdateSetting = "UPDATE ApplicationSettings SET time=@PlatformTime,type=@PlatformType  WHERE ID = @ID;";
    }
}
