using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rally.Framework.Account
{
    public class ModuleConfiguration
    {
        public static string DefaultAccountStoreConnectionName = "DefaultConnection";
        //public static string SQL_CMD_InsertAccount = "INSERT INTO Accounts(Id,Name,FirstName,LastName,NickName,Gender,BirthDate,Title,SID,Address,ZipCode,Email,Mobile,HeadImageFileID,ModifiedDate,Alias,PhoneNumber,PoliticsStatus,Organization,Department,WorkGroup,Position) VALUES (@Id,@Name,@FirstName,@LastName,@NickName,@Gender,@BirthDate,@Title,@SID,@Address,@ZipCode,@Email,@Mobile,@HeadImageFileID,@ModifiedDate,@Alias,@PhoneNumber,@PoliticsStatus,@Organization,@Department,@WorkGroup,@Position);";
        //public static string SQL_CMD_UpdateAccount = "UPDATE Accounts SET FirstName = @FirstName,LastName = @LastName,NickName = @NickName,Gender = @Gender,BirthDate = @BirthDate,Title = @Title,SID = @SID,Address = @Address,ZipCode = @ZipCode,Email = @Email,Mobile = @Mobile,BloodType = @BloodType,Constellation = @Constellation,Hobby = @Hobby,Education = @Education,Industry = @Industry,Organization = @Organization,Department = @Department,WorkGroup = @WorkGroup,Position = @Position,Headline = @Headline,Description = @Description,HeadImageFileID = @HeadImageFileID,ModifiedDate = @ModifiedDate,Alias = @Alias,PhoneNumber = @PhoneNumber,PoliticsStatus = @PoliticsStatus WHERE Id = @Id;";
        //public static string SQL_CMD_UpdateAccountWithUserName = "UPDATE Accounts SET FirstName = @FirstName,LastName = @LastName,Name = @Name,NickName = @NickName,Gender = @Gender,BirthDate = @BirthDate,Title = @Title,SID = @SID,Address = @Address,ZipCode = @ZipCode,Email = @Email,Mobile = @Mobile,BloodType = @BloodType,Constellation = @Constellation,Hobby = @Hobby,Education = @Education,Industry = @Industry,Organization = @Organization,Department = @Department,WorkGroup = @WorkGroup,Position = @Position,Headline = @Headline,Description = @Description,HeadImageFileID = @HeadImageFileID,ModifiedDate = @ModifiedDate,Alias = @Alias,PhoneNumber = @PhoneNumber,PoliticsStatus = @PoliticsStatus WHERE Id = @Id;";
        //public static string SQL_CMD_SelectAccountById = "SELECT Id,Name,FirstName,LastName,NickName,Gender,BirthDate,Title,SID,Address,ZipCode,Email,Mobile,BloodType,Constellation,Hobby,Education,Industry,Organization,Department,WorkGroup,Position,Headline,Description,HeadImageFileID,Alias,PhoneNumber,PoliticsStatus FROM Accounts WHERE Id = @Id;";//QQNumber,WeChatNumber,SinaWeibo,CNKIAccount,SystemAccount,
        //public static string SQL_CMD_SelectAccountByMobile = "SELECT Id,Name,FirstName,LastName,NickName,Gender,BirthDate,Title,SID,Address,ZipCode,Email,Mobile,BloodType,Constellation,Hobby,Education,Industry,Organization,Department,WorkGroup,Position,Headline,Description,HeadImageFileID,Alias,PhoneNumber,PoliticsStatus FROM Accounts WHERE Mobile = @Mobile;";//,QQNumber,WeChatNumber,SinaWeibo,CNKIAccount,SystemAccount
        //public static string SQL_CMD_SelectAccountByNickName = "SELECT Id,Name,FirstName,LastName,NickName,Gender,BirthDate,Title,SID,Address,ZipCode,Email,Mobile,BloodType,Constellation,Hobby,Education,Industry,Organization,Department,WorkGroup,Position,Headline,Description,HeadImageFileID,Alias,PhoneNumber,PoliticsStatus FROM Accounts WHERE NickName = @NickName;";//QQNumber,WeChatNumber,SinaWeibo,CNKIAccount,SystemAccount,
        //public static string SQL_CMD_SelectAccountsAll = "SELECT Id,Name,FirstName,LastName,NickName,Gender,BirthDate,Title,SID,Address,ZipCode,Email,Mobile,BloodType,Constellation,Hobby,Education,Industry,Organization,Department,WorkGroup,Position,Headline,Description,HeadImageFileID,Alias,PhoneNumber,PoliticsStatus FROM Accounts;";
        //public static string SQL_CMD_InsertAccountProvider = "INSERT INTO AccountProviders(Id,Name,AppId,AppSecret,AdditionalInfo,ModifiedDate) VALUES (@Id,@Name,@AppId,@AppSecret,@AdditionalInfo,@ModifiedDate);";
        //public static string SQL_CMD_SelectAccountProviderById = "SELECT Id,Name,AppId,AppSecret,AdditionalInfo FROM AccountProviders WHERE Id = @Id;";
        //public static string SQL_CMD_SelectAccountProviderByAppId = "SELECT Id,Name,AppId,AppSecret,AdditionalInfo FROM AccountProviders WHERE AppId = @AppId;";
        //public static string SQL_CMD_InsertExternalAccount = "INSERT INTO ExternalAccounts(AccountId,ProviderId,Identifier,AdditionalInfo,ModifiedDate) VALUES (@AccountId, @ProviderId,@Identifier, @AdditionalInfo,@ModifiedDate);";
        //public static string SQL_CMD_SelectExternalAccountsByAccountId = "SELECT AccountId,ProviderId,Identifier,AdditionalInfo FROM ExternalAccounts WHERE AccountId = @AccountId;";
        //public static string SQL_CMD_SelectAccountHeadImageById = "SELECT Id,HeadImageFileID FROM Accounts WHERE Id = @Id;";
        //public static string SQL_CMD_DeleteAccount = "DELETE FROM Accounts WHERE Id = @Id;";

        //public static string SQL_CMD_InsertAccount = "INSERT INTO tb_mon_Accounts(Acc_Id,Acc_Name,Acc_FirstName,Acc_LastName,Acc_NickName,Acc_Gender,Acc_BirthDate,Acc_Title,Acc_SID,Acc_Address,Acc_ZipCode,Acc_Email,Acc_Mobile,Acc_HeadImageFileID,Acc_ModifiedDate,Acc_Alias,Acc_PhoneNumber,Acc_PoliticsStatus,Acc_Organization,Acc_Department,Acc_WorkGroup,Acc_Position) VALUES (@Id,@Name,@FirstName,@LastName,@NickName,@Gender,@BirthDate,@Title,@SID,@Address,@ZipCode,@Email,@Mobile,@HeadImageFileID,@ModifiedDate,@Alias,@PhoneNumber,@PoliticsStatus,@Organization,@Department,@WorkGroup,@Position);";
        //public static string SQL_CMD_UpdateAccount = "UPDATE tb_mon_Accounts SET Acc_FirstName = @FirstName,Acc_LastName = @LastName,Acc_NickName = @NickName,Acc_Gender = @Gender,Acc_BirthDate = @BirthDate,Acc_Title = @Title,Acc_SID = @SID,Acc_Address = @Address,Acc_ZipCode = @ZipCode,Acc_Email = @Email,Acc_Mobile = @Mobile,Acc_BloodType = @BloodType,Acc_Constellation = @Constellation,Acc_Hobby = @Hobby,Acc_Education = @Education,Acc_Industry = @Industry,Acc_Organization = @Organization,Acc_Department = @Department,Acc_WorkGroup = @WorkGroup,Acc_Position = @Position,Acc_Headline = @Headline,Acc_Description = @Description,Acc_HeadImageFileID = @HeadImageFileID,Acc_ModifiedDate = @ModifiedDate,Acc_Alias = @Alias,Acc_PhoneNumber = @PhoneNumber,Acc_PoliticsStatus = @PoliticsStatus WHERE Acc_Id = @Id;";
        //public static string SQL_CMD_UpdateAccountWithUserName = "UPDATE tb_mon_Accounts SET Acc_FirstName=@FirstName, Acc_LastName=@LastName, Acc_Name=@Name, Acc_NickName=@NickName, Acc_Gender=@Gender, Acc_BirthDate=@BirthDate, Acc_Title=@Title, Acc_SID=@SID, Acc_Address=@Address, Acc_ZipCode=@ZipCode, Acc_Email=@Email, Acc_Mobile=@Mobile, Acc_BloodType=@BloodType, Acc_Constellation=@Constellation, Acc_Hobby=@Hobby, Acc_Education=@Education, Acc_Industry=@Industry, Acc_Organization=@Organization, Acc_Department=@Department, Acc_WorkGroup=@WorkGroup, Acc_Position=@Position, Acc_Headline=@Headline, Acc_Description=@Description, Acc_HeadImageFileID=@HeadImageFileID, Acc_ModifiedDate=@ModifiedDate, Acc_Alias=@Alias, Acc_PhoneNumber = @PhoneNumber, Acc_PoliticsStatus = @PoliticsStatus WHERE Acc_Id = @Id;";
        //public static string SQL_CMD_SelectAccountById = "SELECT Acc_Id as Id, Acc_Name as Name, Acc_FirstName as FirstName, Acc_LastName as LastName, Acc_NickName as NickName, Acc_Gender as Gender, Acc_BirthDate as BirthDate, Acc_Title as Title, Acc_SID as SID, Acc_Address as Address, Acc_ZipCode as ZipCode, Acc_Email as Email, Acc_Mobile as Mobile, Acc_BloodType as BloodType, Acc_Constellation as Constellation, Acc_Hobby as Hobby, Acc_Education as Education, Acc_Industry as Industry, Acc_Organization as Organization, Acc_Department as Department, Acc_WorkGroup as WorkGroup, Acc_Position as Position, Acc_Headline as Headline, Acc_Description as Description, Acc_HeadImageFileID as HeadImageFileID, Acc_Alias as Alias, Acc_PhoneNumber as PhoneNumber, Acc_PoliticsStatus as PoliticsStatus FROM tb_mon_Accounts WHERE Acc_Id = @Id;";//QQNumber,WeChatNumber,SinaWeibo,CNKIAccount,SystemAccount,
        //public static string SQL_CMD_SelectAccountByMobile = "SELECT Acc_Id as Id, Acc_Name as Name, Acc_FirstName as FirstName, Acc_LastName as LastName, Acc_NickName as NickName, Acc_Gender as Gender, Acc_BirthDate as BirthDate, Acc_Title as Title, Acc_SID as SID, Acc_Address as Address, Acc_ZipCode as ZipCode, Acc_Email as Email, Acc_Mobile as Mobile, Acc_BloodType as BloodType, Acc_Constellation as Constellation, Acc_Hobby as Hobby, Acc_Education as Education, Acc_Industry as Industry, Acc_Organization as Organization, Acc_Department as Department, Acc_WorkGroup as WorkGroup, Acc_Position as Position, Acc_Headline as Headline, Acc_Description as Description, Acc_HeadImageFileID as HeadImageFileID, Acc_Alias as Alias, Acc_PhoneNumber as PhoneNumber, Acc_PoliticsStatus as PoliticsStatus FROM tb_mon_Accounts WHERE Acc_Mobile = @Mobile;";//,QQNumber,WeChatNumber,SinaWeibo,CNKIAccount,SystemAccount
        //public static string SQL_CMD_SelectAccountByNickName = "SELECT Acc_Id as Id, Acc_Name as Name, Acc_FirstName as FirstName, Acc_LastName as LastName, Acc_NickName as NickName, Acc_Gender as Gender, Acc_BirthDate as BirthDate, Acc_Title as Title, Acc_SID as SID, Acc_Address as Address, Acc_ZipCode as ZipCode, Acc_Email as Email, Acc_Mobile as Mobile, Acc_BloodType as BloodType, Acc_Constellation as Constellation, Acc_Hobby as Hobby, Acc_Education as Education, Acc_Industry as Industry, Acc_Organization as Organization, Acc_Department as Department, Acc_WorkGroup as WorkGroup, Acc_Position as Position, Acc_Headline as Headline, Acc_Description as Description, Acc_HeadImageFileID as HeadImageFileID, Acc_Alias as Alias, Acc_PhoneNumber as PhoneNumber, Acc_PoliticsStatus as PoliticsStatus FROM tb_mon_Accounts WHERE Acc_NickName = @NickName;";//QQNumber,WeChatNumber,SinaWeibo,CNKIAccount,SystemAccount,
        //public static string SQL_CMD_SelectAccountsAll = "SELECT Acc_Id as Id, Acc_Name as Name, Acc_FirstName as FirstName, Acc_LastName as LastName, Acc_NickName as NickName, Acc_Gender as Gender, Acc_BirthDate as BirthDate, Acc_Title as Title, Acc_SID as SID, Acc_Address as Address, Acc_ZipCode as ZipCode, Acc_Email as Email, Acc_Mobile as Mobile, Acc_BloodType as BloodType, Acc_Constellation as Constellation, Acc_Hobby as Hobby, Acc_Education as Education, Acc_Industry as Industry, Acc_Organization as Organization, Acc_Department as Department, Acc_WorkGroup as WorkGroup, Acc_Position as Position, Acc_Headline as Headline, Acc_Description as Description, Acc_HeadImageFileID as HeadImageFileID, Acc_Alias as Alias, Acc_PhoneNumber as PhoneNumber, Acc_PoliticsStatus as PoliticsStatus FROM tb_mon_Accounts;";
        //public static string SQL_CMD_InsertAccountProvider = "INSERT INTO AccountProviders(Id,Name,AppId,AppSecret,AdditionalInfo,ModifiedDate) VALUES (@Id,@Name,@AppId,@AppSecret,@AdditionalInfo,@ModifiedDate);";
        //public static string SQL_CMD_SelectAccountProviderById = "SELECT Id,Name,AppId,AppSecret,AdditionalInfo FROM AccountProviders WHERE Id = @Id;";
        //public static string SQL_CMD_SelectAccountProviderByAppId = "SELECT Id,Name,AppId,AppSecret,AdditionalInfo FROM AccountProviders WHERE AppId = @AppId;";
        //public static string SQL_CMD_InsertExternalAccount = "INSERT INTO ExternalAccounts(AccountId,ProviderId,Identifier,AdditionalInfo,ModifiedDate) VALUES (@AccountId, @ProviderId,@Identifier, @AdditionalInfo,@ModifiedDate);";
        //public static string SQL_CMD_SelectExternalAccountsByAccountId = "SELECT AccountId,ProviderId,Identifier,AdditionalInfo FROM ExternalAccounts WHERE AccountId = @AccountId;";
        //public static string SQL_CMD_SelectAccountHeadImageById = "SELECT Acc_Id,Acc_HeadImageFileID FROM tb_mon_Accounts WHERE Acc_Id = @Id;";
        //public static string SQL_CMD_DeleteAccount = "DELETE FROM tb_mon_Accounts WHERE Acc_Id = @Id;";

        public static string SQL_CMD_InsertAccount = "INSERT INTO Accounts(Id,Name,FirstName,LastName,NickName,Gender,BirthDate,Title,SID,Address,ZipCode,Email,Mobile,HeadImageFileID,ModifiedDate,Alias,PhoneNumber,PoliticsStatus,Organization,Department,WorkGroup,Position) VALUES (@Id,@Name,@FirstName,@LastName,@NickName,@Gender,@BirthDate,@Title,@SID,@Address,@ZipCode,@Email,@Mobile,@HeadImageFileID,@ModifiedDate,@Alias,@PhoneNumber,@PoliticsStatus,@Organization,@Department,@WorkGroup,@Position);";
        public static string SQL_CMD_UpdateAccount = "UPDATE Accounts SET FirstName = @FirstName,LastName = @LastName,NickName = @NickName,Gender = @Gender,BirthDate = @BirthDate,Title = @Title,SID = @SID,Address = @Address,ZipCode = @ZipCode,Email = @Email,Mobile = @Mobile,BloodType = @BloodType,Constellation = @Constellation,Hobby = @Hobby,Education = @Education,Industry = @Industry,Organization = @Organization,Department = @Department,WorkGroup = @WorkGroup,Position = @Position,Headline = @Headline,Description = @Description,HeadImageFileID = @HeadImageFileID,ModifiedDate = @ModifiedDate,Alias = @Alias,PhoneNumber = @PhoneNumber,PoliticsStatus = @PoliticsStatus WHERE Id = @Id;";
        public static string SQL_CMD_UpdateAccountWithUserName = "UPDATE Accounts SET FirstName=@FirstName, LastName=@LastName, Name=@Name, NickName=@NickName, Gender=@Gender, BirthDate=@BirthDate, Title=@Title,SID=@SID, Address=@Address, ZipCode=@ZipCode, Email=@Email, Mobile=@Mobile, BloodType=@BloodType, Constellation=@Constellation, Hobby=@Hobby, Education=@Education, Industry=@Industry, Organization=@Organization, Department=@Department, WorkGroup=@WorkGroup, Position=@Position, Headline=@Headline, Description=@Description, HeadImageFileID=@HeadImageFileID, ModifiedDate=@ModifiedDate, Alias=@Alias, PhoneNumber = @PhoneNumber, PoliticsStatus = @PoliticsStatus WHERE Id = @Id;";
        public static string SQL_CMD_SelectAccountById = "SELECT Id as Id, Name as Name, FirstName as FirstName, LastName as LastName, NickName as NickName, Gender as Gender, BirthDate as BirthDate, Title as Title, SID as SID, Address as Address, ZipCode as ZipCode, Email as Email, Mobile as Mobile, BloodType as BloodType, Constellation as Constellation, Hobby as Hobby, Education as Education, Industry as Industry, Organization as Organization, Department as Department, WorkGroup as WorkGroup, Position as Position, Headline as Headline, Description as Description, HeadImageFileID as HeadImageFileID, Alias as Alias, PhoneNumber as PhoneNumber, PoliticsStatus as PoliticsStatus FROM Accounts WHERE Id = @Id;";//QQNumber,WeChatNumber,SinaWeibo,CNKIAccount,SystemAccount,
        public static string SQL_CMD_SelectAccountByMobile = "SELECT Id as Id, Name as Name, FirstName as FirstName, LastName as LastName, NickName as NickName, Gender as Gender, BirthDate as BirthDate, Title as Title, SID as SID, Address as Address, ZipCode as ZipCode, Email as Email, Mobile as Mobile, BloodType as BloodType, Constellation as Constellation, Hobby as Hobby, Education as Education, Industry as Industry, Organization as Organization, Department as Department, WorkGroup as WorkGroup, Position as Position, Headline as Headline, Description as Description, HeadImageFileID as HeadImageFileID, Alias as Alias, PhoneNumber as PhoneNumber, PoliticsStatus as PoliticsStatus FROM Accounts WHERE Mobile = @Mobile;";//,QQNumber,WeChatNumber,SinaWeibo,CNKIAccount,SystemAccount
        public static string SQL_CMD_SelectAccountByNickName = "SELECT Id as Id, Name as Name, FirstName as FirstName, LastName as LastName, NickName as NickName, Gender as Gender, BirthDate as BirthDate, Title as Title, SID as SID, Address as Address, ZipCode as ZipCode, Email as Email, Mobile as Mobile, BloodType as BloodType, Constellation as Constellation, Hobby as Hobby, Education as Education, Industry as Industry, Organization as Organization, Department as Department, WorkGroup as WorkGroup, Position as Position, Headline as Headline, Description as Description, HeadImageFileID as HeadImageFileID, Alias as Alias, PhoneNumber as PhoneNumber, PoliticsStatus as PoliticsStatus FROM Accounts WHERE NickName = @NickName;";//QQNumber,WeChatNumber,SinaWeibo,CNKIAccount,SystemAccount,
        public static string SQL_CMD_SelectAccountsAll = "SELECT Id as Id, Name as Name, FirstName as FirstName, LastName as LastName, NickName as NickName, Gender as Gender, BirthDate as BirthDate, Title as Title, SID as SID, Address as Address, ZipCode as ZipCode, Email as Email, Mobile as Mobile, BloodType as BloodType, Constellation as Constellation, Hobby as Hobby, Education as Education, Industry as Industry, Organization as Organization, Department as Department, WorkGroup as WorkGroup, Position as Position, Headline as Headline, Description as Description, HeadImageFileID as HeadImageFileID, Alias as Alias, PhoneNumber as PhoneNumber, PoliticsStatus as PoliticsStatus FROM Accounts;";
        public static string SQL_CMD_InsertAccountProvider = "INSERT INTO AccountProviders(Id,Name,AppId,AppSecret,AdditionalInfo,ModifiedDate) VALUES (@Id,@Name,@AppId,@AppSecret,@AdditionalInfo,@ModifiedDate);";
        public static string SQL_CMD_SelectAccountProviderById = "SELECT Id,Name,AppId,AppSecret,AdditionalInfo FROM AccountProviders WHERE Id = @Id;";
        public static string SQL_CMD_SelectAccountProviderByAppId = "SELECT Id,Name,AppId,AppSecret,AdditionalInfo FROM AccountProviders WHERE AppId = @AppId;";
        public static string SQL_CMD_InsertExternalAccount = "INSERT INTO ExternalAccounts(AccountId,ProviderId,Identifier,AdditionalInfo,ModifiedDate) VALUES (@AccountId, @ProviderId,@Identifier, @AdditionalInfo,@ModifiedDate);";
        public static string SQL_CMD_SelectExternalAccountsByAccountId = "SELECT AccountId,ProviderId,Identifier,AdditionalInfo FROM ExternalAccounts WHERE AccountId = @AccountId;";
        public static string SQL_CMD_SelectAccountHeadImageById = "SELECT Id,HeadImageFileID FROM Accounts WHERE Id = @Id;";
        public static string SQL_CMD_DeleteAccount = "DELETE FROM Accounts WHERE Id = @Id;";
    }
}
