using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rally.Framework.Maintenance
{
    public class ModuleConfiguration
    {
        //public static string SQL_CMD_InsertInstrumentFault = "INSERT INTO instrument_faults (InstrumentID, FaultTime, FaultType, FaultCode, FaultMessage) VALUES (@InstrumentID, @FaultTime, @FaultType, @FaultCode, @FaultMessage);";
        //public static string SQL_CMD_SelectInstrumentFault = "SELECT ID, InstrumentID, FaultTime, FaultType, FaultCode, FaultMessage FROM instrument_faults WHERE InstrumentID = @InstrumentID;";
        //public static string SQL_CMD_SelectFaultById = "SELECT ID, InstrumentID, FaultTime, FaultType, FaultCode, FaultMessage FROM instrument_faults WHERE ID = @ID;";
        //public static string SQL_CMD_InsertMaintenanceOrder = "INSERT INTO maintenance_orders (InstrumentID, OrderRefID, OrderDate, FaultTime, WarrantyStatus, Cost, FaultCode, FaultDescription, RepairResult, RepairDescription, UserComment, CommentContent) VALUES (@InstrumentID, @OrderRefID, @OrderDate, @FaultTime, @WarrantyStatus, @Cost, @FaultCode, @FaultDescription, @RepairResult, @RepairDescription, @UserComment, @CommentContent);";
        //public static string SQL_CMD_UpdateMaintenanceOrder = "UPDATE maintenance_orders SET InstrumentID = @InstrumentID, OrderRefID = @OrderRefID, OrderDate = @OrderDate, FaultTime = @FaultTime, WarrantyStatus = @WarrantyStatus, Cost = @Cost, FaultCode = @FaultCode, FaultDescription = @FaultDescription, RepairResult = @RepairResult, RepairDescription = @RepairDescription, UserComment = @UserComment, CommentContent = @CommentContent WHERE ID = @ID;";
        //public static string SQL_CMD_SelectMaintenanceOrderById = "SELECT ID, InstrumentID, OrderRefID, OrderDate, FaultTime, WarrantyStatus, Cost, FaultCode, FaultDescription, RepairResult, RepairDescription, UserComment, CommentContent FROM maintenance_orders WHERE ID = @ID;";
        //public static string SQL_CMD_SelectInstrumentMaintenanceOrder = "SELECT ID, InstrumentID, OrderRefID, OrderDate, FaultTime, WarrantyStatus, Cost, FaultCode, FaultDescription, RepairResult, RepairDescription, UserComment, CommentContent FROM maintenance_orders WHERE InstrumentID = @InstrumentID;";
        //public static string SQL_CMD_InsertMaintenanceOrderLineItem = "INSERT INTO tb_mon_MaintenanceOrderLineitems (OrderID, FulfillmentDate, Notes, RepairResult) VALUES (@OrderID, @FulfillmentDate, @Notes, @RepairResult);";
        //public static string SQL_CMD_UpdateMaintenanceOrderLineItem = "UPDATE tb_mon_MaintenanceOrderLineitems SET  Notes = @Notes WHERE ID = @ID;";
        //public static string SQL_CMD_SelectInstrumentMaintenanceOrderLineItem = "SELECT ID, OrderID, FulfillmentDate, Notes, RepairResult FROM tb_mon_MaintenanceOrderLineitems WHERE OrderID = @OrderID;";
        //public static string SQL_CMD_InsertMaintenanceOrderAttachment = "INSERT INTO maintenance_order_attachments (OrderID, FileID, FileCreationTime) VALUES (@OrderID, @FileID, @FileCreationTime);";
        //public static string SQL_CMD_SelectMaintenanceOrderAttachment = "SELECT ID, OrderID, FileID, FileCreationTime FROM maintenance_order_attachments WHERE OrderID = @OrderID;";
        //public static string SQL_CMD_SelectMaxInstrumentFaultID = "SELECT MAX(ID) FROM instruments_faults";
        //public static string SQL_CMD_SelectMaxMaintenanceOrderID = "SELECT MAX(ID) FROM maintenance_orders";
        //public static string SQL_CMD_SelectMaxMaintenanceeOrderLineItemID = "SELECT MAX(ID) FROM tb_mon_MaintenanceOrderLineitems";
        //public static string SQL_CMD_SelectMaxMaintenanceOrderAttachmentID = "SELECT MAX(ID) FROM maintenance_order_attachments";
        //public static string SQL_CMD_MaintenanceOrderData = "SELECT CASE `RepairResult` WHEN '0' THEN '维修成功' WHEN '1' THEN '维修失败' END AS RepairResult,A.ID, InstrumentID, OrderRefID, OrderDate, FaultTime,Cost, FaultCode, FaultDescription, RepairResult, RepairDescription, UserComment, CommentContent,SerialNumber FROM maintenance_orders A,instruments B WHERE B.ID = A.InstrumentID ";
        //public static string SQL_CMD_DeleteMaintenanceOrder = "DELETE FROM maintenance_orders WHERE ID = @ID;";
        //public static string SQL_CMD_DeleteMaintenanceOrderLineitems = "DELETE FROM tb_mon_MaintenanceOrderLineitems WHERE OrderID = @OrderID;";
        //public static string SQL_CMD_DeleteMaintenanceOrderLineitems1 = "DELETE FROM tb_mon_MaintenanceOrderLineitems WHERE ID = @ID;";
        //public static string SQL_CMD_DeleteMaintenanceOrderAttachment = "DELETE FROM maintenance_order_attachments WHERE ID = @ID;";

        //public static string SQL_CMD_InsertInstrumentFault = "INSERT INTO tb_mon_InstrumentFaults (Ins_InstrumentID, ifa_FaultTime, ifa_FaultType, ifa_FaultCode, ifa_FaultMessage) VALUES (@InstrumentID, @FaultTime, @FaultType, @FaultCode, @FaultMessage);";
        //public static string SQL_CMD_SelectInstrumentFault = "SELECT ifa_ID as ID, Ins_InstrumentID as InstrumentID, ifa_FaultTime as FaultTime, ifa_FaultType as FaultType, ifa_FaultCode as FaultCode, ifa_FaultMessage as FaultMessage FROM tb_mon_InstrumentFaults WHERE Ins_InstrumentID = @InstrumentID;";
        //public static string SQL_CMD_SelectFaultById = "SELECT  ifa_ID as ID,  ifa_InstrumentID as InstrumentID, ifa_FaultTime as FaultTime,ifa_FaultType as FaultType,ifa_FaultCode as FaultCode, ifa_FaultMessage as FaultMessage FROM tb_mon_InstrumentFaults WHERE ifa_ID = @ID;";
        //public static string SQL_CMD_InsertMaintenanceOrder = "INSERT INTO tb_mon_MaintenanceOrders (Ins_InstrumentID, mor_OrderRefID, mor_OrderDate, mor_FaultTime, mor_WarrantyStatus, mor_Cost, mor_FaultCode, mor_FaultDescription, mor_RepairResult, mor_RepairDescription, mor_UserComment, mor_CommentContent) VALUES (@InstrumentID, @OrderRefID, @OrderDate, @FaultTime, @WarrantyStatus, @Cost, @FaultCode, @FaultDescription, @RepairResult, @RepairDescription, @UserComment, @CommentContent);";
        //public static string SQL_CMD_UpdateMaintenanceOrder = "UPDATE tb_mon_MaintenanceOrders SET Ins_InstrumentID = @InstrumentID, mor_OrderRefID = @OrderRefID, mor_OrderDate = @OrderDate, mor_FaultTime = @FaultTime, mor_WarrantyStatus = @WarrantyStatus, mor_Cost = @Cost, mor_FaultCode = @FaultCode, mor_FaultDescription = @FaultDescription, mor_RepairResult = @RepairResult, mor_RepairDescription = @RepairDescription, mor_UserComment = @UserComment, mor_CommentContent = @CommentContent WHERE mor_ID = @ID;";
        //public static string SQL_CMD_SelectMaintenanceOrderById = "SELECT mor_ID as ID, Ins_InstrumentID as InstrumentID, mor_OrderRefID as OrderRefID, mor_OrderDate as OrderDate, mor_FaultTime as FaultTime, mor_WarrantyStatus as WarrantyStatus, mor_Cost as Cost, mor_FaultCode as FaultCode, mor_FaultDescription as FaultDescription, mor_RepairResult as RepairResult, mor_RepairDescription as RepairDescription, mor_UserComment as UserComment, mor_CommentContent as CommentContent FROM tb_mon_MaintenanceOrders WHERE mor_ID = @ID;";
        //public static string SQL_CMD_SelectInstrumentMaintenanceOrder = "SELECT mor_ID as ID, Ins_InstrumentID as InstrumentID, mor_OrderRefID as OrderRefID, mor_OrderDate as OrderDate, mor_FaultTime as FaultTime, mor_WarrantyStatus as WarrantyStatus, mor_Cost as Cost, mor_FaultCode as FaultCode, mor_FaultDescription as FaultDescriptionn, mor_RepairResult as RepairResult, mor_RepairDescription as RepairDescription, mor_UserComment as UserComment, mor_CommentContent as CommentContent FROM tb_mon_MaintenanceOrders WHERE Ins_InstrumentID = @InstrumentID;";
        //public static string SQL_CMD_InsertMaintenanceOrderLineItem = "INSERT INTO tb_mon_MaintenanceOrderLineitems (mor_OrderID, mol_FulfillmentDate, mol_Notes, mol_RepairResult) VALUES (@OrderID, @FulfillmentDate, @Notes, @RepairResult);";
        //public static string SQL_CMD_UpdateMaintenanceOrderLineItem = "UPDATE tb_mon_MaintenanceOrderLineitems SET  mol_Notes = @Notes WHERE mol_ID = @ID;";
        //public static string SQL_CMD_SelectInstrumentMaintenanceOrderLineItem = "SELECT mol_ID, mor_OrderID, mol_FulfillmentDate, mol_Notes, mol_RepairResult FROM tb_mon_MaintenanceOrderLineitems WHERE mor_OrderID = @OrderID;";
        //public static string SQL_CMD_InsertMaintenanceOrderAttachment = "INSERT INTO tb_mon_MaintenanceOrderAttachments (mor_OrderID, File_FileID, mat_FileCreationTime) VALUES (@OrderID, @FileID, @FileCreationTime);";
        //public static string SQL_CMD_SelectMaintenanceOrderAttachment = "SELECT mat_ID as ID, mor_OrderID as OrderID, File_FileID as FileID, mat_FileCreationTime as FileCreationTime FROM tb_mon_MaintenanceOrderAttachments WHERE mor_OrderID = @OrderID;";
        //public static string SQL_CMD_SelectMaxInstrumentFaultID = "SELECT MAX(ifa_ID) FROM tb_mon_InstrumentFaults"; 
        //public static string SQL_CMD_SelectMaxMaintenanceOrderID = "SELECT MAX(mor_ID) FROM tb_mon_MaintenanceOrders";
        //public static string SQL_CMD_SelectMaxMaintenanceeOrderLineItemID = "SELECT MAX(mol_ID) FROM tb_mon_MaintenanceOrderLineitems";
        //public static string SQL_CMD_SelectMaxMaintenanceOrderAttachmentID = "SELECT MAX(mat_ID) FROM tb_mon_MaintenanceOrderAttachments";
        //public static string SQL_CMD_MaintenanceOrderData = "SELECT CASE mor_RepairResult WHEN '0' THEN '维修成功' WHEN '1' THEN '维修失败' END AS RepairResult, A.mor_ID as ID, Ins_InstrumentID as InstrumentID, mor_OrderRefID as OrderRefID, mor_OrderDate as OrderDate, mor_FaultTime as FaultTime, mor_Cost as Cost, mor_FaultCode as FaultTime, mor_FaultDescription as FaultDescription, mor_RepairResult as RepairResult, mor_RepairDescription as RepairDescription, mor_UserComment as UserComment, mor_CommentContent as CommentContent, Ins_SerialNumber as SerialNumber FROM tb_mon_MaintenanceOrders A, tb_mon_instruments B WHERE B.Ins_ID = A.Ins_InstrumentID";
        //public static string SQL_CMD_DeleteMaintenanceOrder = "DELETE FROM tb_mon_MaintenanceOrders WHERE mor_ID = @ID;";
        //public static string SQL_CMD_DeleteMaintenanceOrderLineitems = "DELETE FROM tb_mon_MaintenanceOrderLineitems WHERE mor_OrderID = @OrderID;";
        //public static string SQL_CMD_DeleteMaintenanceOrderLineitems1 = "DELETE FROM tb_mon_MaintenanceOrderLineitems WHERE mol_ID = @ID;";
        //public static string SQL_CMD_DeleteMaintenanceOrderAttachment = "DELETE FROM tb_mon_MaintenanceOrderAttachments WHERE mat_ID = @ID;";

        public static string SQL_CMD_InsertInstrumentFault = "INSERT INTO InstrumentFaults (InstrumentID, FaultTime, FaultType, FaultCode, FaultMessage) VALUES (@InstrumentID, @FaultTime, @FaultType, @FaultCode, @FaultMessage);";
        public static string SQL_CMD_SelectInstrumentFault = "SELECT ID as ID, InstrumentID as InstrumentID, FaultTime as FaultTime, FaultType as FaultType, FaultCode as FaultCode, FaultMessage as FaultMessage FROM InstrumentFaults WHERE InstrumentID = @InstrumentID;";
        public static string SQL_CMD_SelectFaultById = "SELECT  ID as ID,  InstrumentID as InstrumentID, FaultTime as FaultTime,FaultType as FaultType,FaultCode as FaultCode, FaultMessage as FaultMessage FROM InstrumentFaults WHERE ID = @ID;";
        public static string SQL_CMD_InsertMaintenanceOrder = "INSERT INTO MaintenanceOrders (InstrumentID, OrderRefID, OrderDate, FaultTime, WarrantyStatus, Cost, FaultCode, FaultDescription, RepairResult, RepairDescription, UserComment, CommentContent) VALUES (@InstrumentID, @OrderRefID, @OrderDate, @FaultTime, @WarrantyStatus, @Cost, @FaultCode, @FaultDescription, @RepairResult, @RepairDescription, @UserComment, @CommentContent);";
        public static string SQL_CMD_UpdateMaintenanceOrder = "UPDATE MaintenanceOrders SET InstrumentID = @InstrumentID, OrderRefID = @OrderRefID, OrderDate = @OrderDate, FaultTime = @FaultTime, WarrantyStatus = @WarrantyStatus, Cost = @Cost, FaultCode = @FaultCode, FaultDescription = @FaultDescription, RepairResult = @RepairResult, RepairDescription = @RepairDescription, UserComment = @UserComment, CommentContent = @CommentContent WHERE ID = @ID;";
        public static string SQL_CMD_SelectMaintenanceOrderById = "SELECT ID as ID, InstrumentID as InstrumentID, OrderRefID as OrderRefID, OrderDate as OrderDate, FaultTime as FaultTime, WarrantyStatus as WarrantyStatus, Cost as Cost, FaultCode as FaultCode, FaultDescription as FaultDescription, RepairResult as RepairResult, RepairDescription as RepairDescription, UserComment as UserComment, CommentContent as CommentContent FROM MaintenanceOrders WHERE ID = @ID;";
        public static string SQL_CMD_SelectInstrumentMaintenanceOrder = "SELECT ID as ID, InstrumentID as InstrumentID, OrderRefID as OrderRefID, OrderDate as OrderDate, FaultTime as FaultTime, WarrantyStatus as WarrantyStatus, Cost as Cost, FaultCode as FaultCode, FaultDescription as FaultDescriptionn, RepairResult as RepairResult, RepairDescription as RepairDescription, UserComment as UserComment, CommentContent as CommentContent FROM MaintenanceOrders WHERE InstrumentID = @InstrumentID;";
        public static string SQL_CMD_InsertMaintenanceOrderLineItem = "INSERT INTO MaintenanceOrderLineitems (OrderID, FulfillmentDate, Notes, RepairResult) VALUES (@OrderID, @FulfillmentDate, @Notes, @RepairResult);";
        public static string SQL_CMD_UpdateMaintenanceOrderLineItem = "UPDATE MaintenanceOrderLineitems SET  Notes = @Notes WHERE ID = @ID;";
        public static string SQL_CMD_SelectInstrumentMaintenanceOrderLineItem = "SELECT ID, OrderID, FulfillmentDate, Notes, RepairResult FROM MaintenanceOrderLineitems WHERE OrderID = @OrderID;";
        public static string SQL_CMD_InsertMaintenanceOrderAttachment = "INSERT INTO MaintenanceOrderAttachments (OrderID, FileID, FileCreationTime) VALUES (@OrderID, @FileID, @FileCreationTime);";
        public static string SQL_CMD_SelectMaintenanceOrderAttachment = "SELECT ID as ID, OrderID as OrderID, FileID as FileID, FileCreationTime as FileCreationTime FROM MaintenanceOrderAttachments WHERE OrderID = @OrderID;";
        public static string SQL_CMD_SelectMaxInstrumentFaultID = "SELECT MAX(ID) FROM InstrumentFaults";
        public static string SQL_CMD_SelectMaxMaintenanceOrderID = "SELECT MAX(ID) FROM MaintenanceOrders";
        public static string SQL_CMD_SelectMaxMaintenanceeOrderLineItemID = "SELECT MAX(ID) FROM MaintenanceOrderLineitems";
        public static string SQL_CMD_SelectMaxMaintenanceOrderAttachmentID = "SELECT MAX(ID) FROM MaintenanceOrderAttachments";
        public static string SQL_CMD_MaintenanceOrderData = "SELECT CASE RepairResult WHEN '0' THEN '维修成功' WHEN '1' THEN '维修失败' END AS RepairResult, A.ID as ID, InstrumentID as InstrumentID, OrderRefID as OrderRefID, OrderDate as OrderDate, FaultTime as FaultTime, Cost as Cost, FaultCode as FaultTime, FaultDescription as FaultDescription, RepairResult as RepairResult, RepairDescription as RepairDescription, UserComment as UserComment, CommentContent as CommentContent, SerialNumber as SerialNumber FROM MaintenanceOrders A, instruments B WHERE B.ID = A.InstrumentID";
        public static string SQL_CMD_DeleteMaintenanceOrder = "DELETE FROM MaintenanceOrders WHERE ID = @ID;";
        public static string SQL_CMD_DeleteMaintenanceOrderLineitems = "DELETE FROM MaintenanceOrderLineitems WHERE OrderID = @OrderID;";
        public static string SQL_CMD_DeleteMaintenanceOrderLineitems1 = "DELETE FROM MaintenanceOrderLineitems WHERE ID = @ID;";
        public static string SQL_CMD_DeleteMaintenanceOrderAttachment = "DELETE FROM MaintenanceOrderAttachments WHERE ID = @ID;";
    }
}
